### ISSUE TITLE
Please update the source code to the latest version

### ISSUE THREAD

**Issue by Stanley00** [csekri/fenix-calculator#1]
Hello, thanks for your great work on this project.

I saw that you have just published new version on Garmin Connect store but the current source code in this repo is not synced up. I would like to contribute to this project, so please make the source code up to date with the version on the Connect store.

Regards,

**Comment by csekri** [comment]
Hi, thanks for your interest.
I've committed and uploaded the latest version (github & Connect IQ). Please note that my last Connect IQ update was in September, the indication of last update in the store must have encountered a glitch. I had to update a little in the source caused by backward compatibility issues in the SDK, unseen when I saw the code last time. The code was tested in the latest SDK version.
Any questions, please ask. Good luck!

**Comment by Stanley00** [comment]
Thanks for your update.

I was planning on adding some "programmable" features for rpn mode. Let me see if I can finish it.
